name       : cargo-c
version    : 0.9.8
release    : 21
source     :
    - https://github.com/lu-zero/cargo-c/archive/refs/tags/v0.9.8.tar.gz : 7c649061826e0ad3c2c8735718f4a0c4afd12eed9b9fdc5fe59e34582902e1c5
    - https://github.com/lu-zero/cargo-c/releases/download/v0.9.8/Cargo.lock : 11f23a09ef06ca2125027e24574124a99089863fb4226570b6adbe317848b670
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - pkgconfig(libcurl)
    - cargo
rundeps    :
    - cargo
networking : yes
setup      : |
    cp $sources/Cargo.lock ./Cargo.lock
build      : |
    cargo build --locked --release
install    : |
    cargo install \
        --locked \
        --no-track \
        --path . \
        --root=$installdir/usr
