name       : cargo-c
version    : 0.6.13
release    : 6
source     :
    - https://github.com/lu-zero/cargo-c/archive/v0.6.13.tar.gz : aa6b23c7ae19ec93e6edeb59be46056faccb915a02d1784a0c29ac7a3c6a8aea
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - cargo
rundeps    :
    - cargo
networking : yes
build      : |
    cargo build --release
install    : |
    cargo install \
        --no-track \
        --path . \
        --root=$installdir/usr
