name       : cargo-c
version    : 0.9.19
release    : 27
source     :
    - https://github.com/lu-zero/cargo-c/archive/refs/tags/v0.9.19.tar.gz : c2633ff22e52da9985394f30c8ef5e9abbac4d14c9b79e3690c8e95cf500ab97
    - https://github.com/lu-zero/cargo-c/releases/download/v0.9.19/Cargo.lock : 7dc8d68efcda151e0b284654c9ca0a17af4cc8bbf4db88342297b016361ef0d3
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - pkgconfig(libcurl)
    - cargo
rundeps    :
    - cargo
networking : yes
setup      : |
    cp $sources/Cargo.lock ./Cargo.lock
build      : |
    cargo build --locked --release
install    : |
    cargo install \
        --locked \
        --no-track \
        --path . \
        --root=$installdir/usr
