name       : cargo-c
version    : 0.9.4
release    : 18
source     :
    - https://github.com/lu-zero/cargo-c/archive/refs/tags/v0.9.4.tar.gz : 8965b1381f2c6fd040a1b930bebf8d1c12646dd7be43d76a23bcc0edf37887d4
    - https://github.com/lu-zero/cargo-c/releases/download/v0.9.4/Cargo.lock : 05b2ef5b1203880f9c09137067a5a3f9bb1efca1f62f6f9525c80d6922b9f4b9
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - pkgconfig(libcurl)
    - cargo
rundeps    :
    - cargo
networking : yes
setup      : |
    cp $sources/Cargo.lock ./Cargo.lock
build      : |
    cargo build --locked --release
install    : |
    cargo install \
        --locked \
        --no-track \
        --path . \
        --root=$installdir/usr
