name       : cargo-c
version    : 0.9.7
release    : 20
source     :
    - https://github.com/lu-zero/cargo-c/archive/refs/tags/v0.9.7.tar.gz : eead78d26b4e5924e9d750f66f2fef4d706680927542d87c895178fc0be016f0
    - https://github.com/lu-zero/cargo-c/releases/download/v0.9.7/Cargo.lock : 3898341b624517daa50d95bd99e2fa873b15ea803f9e3d6f7edab11427b95de8
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - pkgconfig(libcurl)
    - cargo
rundeps    :
    - cargo
networking : yes
setup      : |
    cp $sources/Cargo.lock ./Cargo.lock
build      : |
    cargo build --locked --release
install    : |
    cargo install \
        --locked \
        --no-track \
        --path . \
        --root=$installdir/usr
