name       : cargo-c
version    : 0.6.9
release    : 3
source     :
    - https://github.com/lu-zero/cargo-c/archive/v0.6.9.tar.gz : d88bad2ada3432b15d2a871a5071f2bd7554beec5ecc4807c91599533de76cb4
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - cargo
rundeps    :
    - cargo
networking : yes
build      : |
    cargo build --release
install    : |
    cargo install \
        --no-track \
        --path . \
        --root=$installdir/usr
