name       : cargo-c
version    : 0.6.8
release    : 2
source     :
    - https://github.com/lu-zero/cargo-c/archive/v0.6.8.tar.gz : ca8cb5e08b0ba5b6eccea1481854829e1b411ebb9885be891a897c27b5a76cba
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - cargo
rundeps    :
    - cargo
networking : yes
build      : |
    cargo build --release
install    : |
    cargo install \
        --no-track \
        --path . \
        --root=$installdir/usr
