name       : cargo-c
version    : 0.9.12
release    : 23
source     :
    - https://github.com/lu-zero/cargo-c/archive/refs/tags/v0.9.12.tar.gz : d700c6cc93d06c5ed7a887f51d87d47e88e783dfc1b28d00b951625c4d3ce509
    - https://github.com/lu-zero/cargo-c/releases/download/v0.9.12/Cargo.lock : c1a035c1e69b980d57f20005802699cf5fb63a02423a40ff1675238781db159e
license    : MIT
component  : programming.tools
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - pkgconfig(libcurl)
    - cargo
rundeps    :
    - cargo
networking : yes
setup      : |
    cp $sources/Cargo.lock ./Cargo.lock
build      : |
    cargo build --locked --release
install    : |
    cargo install \
        --locked \
        --no-track \
        --path . \
        --root=$installdir/usr
